In [7]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier


In [3]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

### Переменная importances будет содержать массив "важностей" признаков. Индекс в этом массиве соответствует индексу признака в данных.

In [5]:
importances = clf.feature_importances_
importances

array([0., 1.])

### Стоит обратить внимание, что данные могут содержать пропуски. Pandas хранит такие значения как nan (not a number). Для того, чтобы проверить, является ли число nan'ом, можно воспользоваться функцией np.isnan.



In [6]:
np.isnan(X)

array([[False, False],
       [False, False],
       [False, False]])

In [53]:
df = pd.read_csv("titanic_data.csv", index_col="PassengerId")
df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [56]:
# Remove all lines with NaN
df = df.dropna()
df.head()


Survived  Pclass  \
PassengerId                     
2                   1       1   
4                   1       1   
7                   0       1   
11                  1       3   
12                  1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
7                                      McCarthy, Mr. Timothy J    male  54.0   
11                             Sandstrom, Miss. Marguerite Rut  female   4.0   
12                                    Bonnell, Miss. Elizabeth  female  58.0   

             SibSp  Parch    Ticket     Fare Cabin Embarked  
PassengerId                                                  
2                1      0  PC 17599  71.2833   C85        C  
4                1      0    113803  53.1000  C123        S  
7                0      0     17463  51.8625   E46        S  
11               1      1   PP 9549  16.7000    G6        S  
12               0      0    113783  26.5500  C103        S

In [61]:
# Оставьте в выборке четыре признака: класс пассажира (Pclass), цену билета (Fare), возраст пассажира (Age) и его пол (Sex).

df_short = df[["Pclass", "Fare", "Age", "Sex"]]
df_short.head()


Pclass     Fare   Age     Sex
PassengerId                               
2                 1  71.2833  38.0  female
4                 1  53.1000  35.0  female
7                 1  51.8625  54.0    male
11                3  16.7000   4.0  female
12                1  26.5500  58.0  female

In [63]:
print(df_short.shape)
print(len(df_short))

(183, 4)
183


In [82]:
# Replace 'female' to 1 and male to 0

df_short.loc[df_short.Sex != 'female', 'female'] = 0
df_short.loc[df_short.Sex == 'female', 'female'] = 1
df_short.head()

Pclass     Fare   Age  Sex  female
PassengerId                                    
2                 1  71.2833  38.0    0     0.0
4                 1  53.1000  35.0    0     0.0
7                 1  51.8625  54.0    1     0.0
11                3  16.7000   4.0    0     0.0
12                1  26.5500  58.0    0     0.0

In [83]:
# Целевая переменная Survived
surv = df["Survived"]
surv.head()

PassengerId
2     1
4     1
7     0
11    1
12    1
Name: Survived, dtype: int64

### Обучите решающее дерево с параметром random_state=241 и остальными параметрами по умолчанию (речь идет о параметрах конструктора DecisionTreeСlassifier).

In [85]:
clf = DecisionTreeClassifier(random_state=241)
clf.fit(df_short, surv)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=241, splitter='best')

In [86]:
importances = clf.feature_importances_
importances

array([0.01793336, 0.30537693, 0.39322081, 0.2834689 , 0.        ])